FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
FPN:
  FPN_ON: true
  MULTILEVEL_ROIS: true
  MULTILEVEL_RPN: true
MODEL:
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  FASTER_RCNN: true
  NUM_CLASSES: 3007
  TYPE: generalized_rcnn
NUM_GPUS: 8
OUTPUT_DIR: .
SOLVER:
  BASE_LR: 0.01
  GAMMA: 0.1
  LR_POLICY: steps_with_decay
  MAX_ITER: 180000
  STEPS:
  - 0
  - 120000
  - 160000
  WEIGHT_DECAY: 0.0001
TEST:
  DATASETS: ('vg3k_cocoaligned_val_hardhat', 'hardhat_uniform_val_vg3k')
  FORCE_JSON_DATASET_EVAL: true
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_POST_NMS_TOP_N: 1000
  RPN_PRE_NMS_TOP_N: 1000
  SCALE: 800
TRAIN:
  BATCH_SIZE_PER_IM: 512
  DATASETS: ('vg3k_cocoaligned_train_hardhat', 'hardhat_uniform_train_vg3k')
  IMS_PER_BATCH: 1
  MAX_SIZE: 1333
  RPN_PRE_NMS_TOP_N: 2000
  SCALES: (800,)
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron/35998814/12_2017_baselines/rpn_R-50-FPN_1x.yaml.08_06_03.Axg0r179/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl
USE_NCCL: false
